[common-etcd]
host = "127.0.0.1:2379"
basePath = "/tinyim_srv"
serverPathLogic = "LogicRpc"
serverPathConnect = "ConnectRpc"
userName = ""
password = ""
connectionTimeout = 5

[common-mysql]
host = "127.0.0.1"
port = 3306
user = "root"
password = "root"
database = "tinyim"
